name: Stale monitor

on:
    schedule:
        - cron: '0 0 * * *'

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
    stale:
        name: Stale
        runs-on: ubuntu-24.04
        permissions:
            issues: write
            pull-requests: write
        timeout-minutes: 5

        steps:
            - name: Mark stale issues and PRs
              uses: actions/stale@b5d41d4e1d5dceea10e7104786b73624c18a190f # v10.2.0
              with:
                  stale-issue-message: >
                      This issue has been automatically marked as stale because it has not had
                      recent activity in the past 180 days. It will be closed in 60 days if no
                      further activity occurs. Thank you for your contribution.
                  stale-pr-message: >
                      This PR has been automatically marked as stale because it has not had
                      recent activity in the past 180 days. It will be closed in 60 days if no
                      further activity occurs.
                  days-before-stale: 180
                  days-before-close: 60
                  stale-issue-label: '[Status] Stale'
                  stale-pr-label: '[Status] Stale'
